baseurl = "https://loudervoice.com/"
title = "LouderVoice Customer Reviews"
#theme = "hugo-universal-theme"
theme = "ananke"
languageCode = "en-us"
publishdir = "docs"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "loudervoice"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-88888-5"

[markup.goldmark.renderer]
unsafe= true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

[[menu.main]]
    name = "Our Reviews"
    url  = "/our-reviews/"
    weight = 4

# Top bar social links menu

[params]
    text_color = ""
    favicon = ""
    site_logo = "img/LouderVoice_Logo_White_Text_2024_Site.png"
    viewMorePostLink = "/blog/"
    author = "LouderVoice"
    defaultKeywords = ["loudervoice", "reviews", "feedback"]
    defaultDescription = "Customer Reviews for your site"

    #Â Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    about_us = '<p><a href="/terms-and-conditions">Terms and Conditions</a></p><p><a href="/privacy-policy">Privacy Policy</a></p><p><a href="/credits">Credits</a></p>'
    copyright = "Copyright (c) 2006 - 2024, Argolon Solutions Ltd; all rights reserved. "

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Argolon Solutions Ltd.</strong>
        <br>Old Chapel
        <br>Bandon
        <br>Co Cork
        <br>
        <strong>Ireland</strong>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on sales@loudervoice.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Some of Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = '<a href="/blog">Read all</a> of our posts about customer reviews and why they make sense for your business. If you have not embraced customer feedback yet, let us help you do so.'
